const TABLES = {
  "question-sets": {
    title: "Bộ đề thi",
    table: "question_sets",
    primaryKey: ["id"],
    orderBy: "id DESC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "set_code", label: "Mã đề", type: "text" },
      { name: "name", label: "Tên bộ đề", type: "text", required: true },
      { name: "access_password", label: "Mật khẩu đề", type: "text" },
      { name: "visibility", label: "Chế độ chia sẻ", type: "select", options: ["private", "public"], required: true },
      { name: "is_active", label: "Đang dùng", type: "boolean" },
    ],
  },
  warmup: {
    title: "Khởi động",
    table: "warmup_questions",
    primaryKey: ["question_set_id", "stt"],
    orderBy: "question_set_id ASC, stt ASC",
    columns: [
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "stt", label: "STT", type: "number", required: true },
      { name: "question", label: "Câu hỏi", type: "textarea", required: true },
      { name: "answer", label: "Đáp án đúng/sai", type: "boolean" },
    ],
  },
  "obstacle-keys": {
    title: "Từ khóa VCNV",
    table: "obstacle_keys",
    primaryKey: ["question_set_id", "stt"],
    orderBy: "question_set_id ASC, stt ASC",
    columns: [
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "stt", label: "STT", type: "number", required: true },
      { name: "question", label: "Câu hỏi từ khóa", type: "textarea", required: true },
      { name: "answer", label: "Từ khóa", type: "text", required: true },
      { name: "cell_count", label: "Số ô", type: "number", required: true },
      { name: "image_path", label: "Link hình ảnh", type: "text" },
    ],
  },
  "obstacle-rows": {
    title: "Hàng ngang VCNV",
    table: "obstacle_rows",
    primaryKey: ["question_set_id", "stt", "row_no"],
    orderBy: "question_set_id ASC, stt ASC, row_no ASC",
    columns: [
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "stt", label: "Mã từ khóa", type: "number", required: true },
      { name: "row_no", label: "Hàng ngang", type: "number", required: true },
      { name: "cell_count", label: "Số ô", type: "number", required: true },
      { name: "question", label: "Câu hỏi", type: "textarea", required: true },
      { name: "answer", label: "Đáp án", type: "text", required: true },
    ],
  },
  speed: {
    title: "Tăng tốc",
    table: "speed_questions",
    primaryKey: ["question_set_id", "stt"],
    orderBy: "question_set_id ASC, stt ASC",
    columns: [
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "stt", label: "STT", type: "number", required: true },
      { name: "question", label: "Câu hỏi", type: "textarea", required: true },
      { name: "answer_a", label: "Đáp án A", type: "text", required: true },
      { name: "answer_b", label: "Đáp án B", type: "text", required: true },
      { name: "answer_c", label: "Đáp án C", type: "text", required: true },
      { name: "answer_d", label: "Đáp án D", type: "text", required: true },
      { name: "answer", label: "Đáp án đúng", type: "select", options: ["A", "B", "C", "D"], required: true },
      { name: "media_path", label: "Media", type: "text" },
    ],
  },
  finish: {
    title: "Về đích",
    table: "finish_questions",
    primaryKey: ["question_set_id", "stt", "point"],
    orderBy: "question_set_id ASC, point ASC, stt ASC",
    columns: [
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "stt", label: "STT", type: "number", required: true },
      { name: "question", label: "Câu hỏi", type: "textarea", required: true },
      { name: "answer_a", label: "Đáp án A", type: "text", required: true },
      { name: "answer_b", label: "Đáp án B", type: "text", required: true },
      { name: "answer_c", label: "Đáp án C", type: "text", required: true },
      { name: "answer_d", label: "Đáp án D", type: "text", required: true },
      { name: "answer", label: "Đáp án đúng", type: "select", options: ["A", "B", "C", "D"], required: true },
      { name: "point", label: "Điểm", type: "select", options: [20, 40], required: true },
    ],
  },
  scores: {
    title: "Bảng điểm",
    table: "scores",
    primaryKey: ["stt"],
    orderBy: "score DESC, stt ASC",
    columns: [
      { name: "stt", label: "STT", type: "number", generated: true },
      { name: "name", label: "Tên", type: "text", required: true },
      { name: "score", label: "Điểm", type: "number", required: true },
    ],
  },
  rooms: {
    title: "Phòng thi / Máy chủ",
    table: "match_rooms",
    primaryKey: ["id"],
    orderBy: "id DESC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "server_slot_id", label: "Server đã chọn", type: "number" },
      { name: "server_name", label: "Tên server", type: "text", required: true },
      { name: "purpose", label: "Mục đích", type: "text", required: true },
      { name: "room_code", label: "Mã phòng", type: "text", required: true },
      { name: "quick_token", label: "Mã chọn server/phòng", type: "text", required: true },
      { name: "login_password", label: "Mật khẩu phòng", type: "text", required: true },
      { name: "recovery_password", label: "Mật khẩu cấp 2", type: "text", required: true },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: ["draft", "scheduled", "live", "paused", "finished", "cancelled"],
        required: true,
      },
      { name: "scheduled_from", label: "Bắt đầu", type: "datetime-local", required: true },
      { name: "scheduled_to", label: "Kết thúc", type: "datetime-local", required: true },
    ],
  },
  contestants: {
    title: "Thí sinh",
    table: "contestants",
    primaryKey: ["id"],
    orderBy: "room_id ASC, seat_no ASC, id ASC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "room_id", label: "Phòng thi", type: "number", required: true },
      { name: "login_code", label: "Mã ID đăng nhập", type: "text", required: true },
      { name: "display_name", label: "Tên thí sinh", type: "text", required: true },
      { name: "school", label: "Trường", type: "text", required: true },
      { name: "avatar_url", label: "Ảnh đại diện", type: "text" },
      { name: "seat_no", label: "Máy số", type: "number", required: true },
      { name: "score", label: "Điểm", type: "number", required: true },
      { name: "is_active", label: "Đang thi", type: "boolean" },
    ],
  },
  media: {
    title: "Media / Âm thanh",
    table: "media_assets",
    primaryKey: ["id"],
    orderBy: "id DESC",
    allowUpload: true,
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "question_set_id", label: "Bộ đề", type: "number" },
      { name: "title", label: "Tên media", type: "text", required: true },
      { name: "media_type", label: "Loại media", type: "select", options: ["image", "audio", "video", "theme"], required: true },
      { name: "url", label: "URL", type: "text" },
      { name: "local_path", label: "Tệp đã tải lên", type: "text" },
      { name: "duration_seconds", label: "Số giây", type: "number" },
    ],
  },
  "server-slots": {
    title: "Danh sách máy chủ",
    table: "server_slots",
    primaryKey: ["id"],
    orderBy: "sort_order ASC, id ASC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "server_key", label: "Mã máy chủ", type: "text", required: true },
      { name: "display_name", label: "Tên máy chủ", type: "text", required: true },
      { name: "is_primary", label: "Máy chủ chính", type: "boolean" },
      { name: "status", label: "Trạng thái", type: "select", options: ["available", "booked", "maintenance"], required: true },
      { name: "sort_order", label: "Thứ tự", type: "number" },
    ],
  },
  "room-settings": {
    title: "Cài đặt phòng realtime",
    table: "room_settings",
    primaryKey: ["room_id"],
    orderBy: "room_id DESC",
    columns: [
      { name: "room_id", label: "ID phòng", type: "number", required: true },
      { name: "contest_title", label: "Tên cuộc thi", type: "text", required: true },
      { name: "show_logo", label: "Hiển thị logo", type: "boolean" },
      { name: "scoreboard_mode", label: "Bảng điểm", type: "select", options: ["names", "scores", "both"], required: true },
      { name: "allow_negative_score", label: "Cho điểm âm", type: "boolean" },
      { name: "candidate_count", label: "Số thí sinh", type: "number" },
      { name: "active_round", label: "Phần thi", type: "select", options: ["setup", "warmup", "obstacle", "speed", "finish", "tie_breaker", "jeopardy", "connecting_wall", "summary"] },
      { name: "current_question_text", label: "Câu hỏi hiện tại", type: "textarea" },
      { name: "current_answer", label: "Đáp án hiện tại", type: "textarea" },
      { name: "current_media_url", label: "Media hiện tại", type: "text" },
      { name: "timer_seconds", label: "Đồng hồ", type: "number" },
      { name: "ring_delay_seconds", label: "Độ trễ chuông", type: "number" },
      { name: "ring_locked", label: "Khóa chuông", type: "boolean" },
      { name: "star_confirmed", label: "Đã chốt sao", type: "boolean" },
      { name: "star_enabled", label: "Có Ngôi sao hy vọng", type: "boolean" },
      { name: "projector_mode", label: "Chế độ máy chiếu", type: "select", options: ["clean", "projector", "overlay"] },
      { name: "mc_notice", label: "Thông báo MC", type: "textarea" },
    ],
  },
  answers: {
    title: "Đáp án thí sinh",
    table: "answer_submissions",
    primaryKey: ["id"],
    orderBy: "id DESC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "room_id", label: "Phòng", type: "number", required: true },
      { name: "contestant_id", label: "Thí sinh", type: "number" },
      { name: "round_key", label: "Phần thi", type: "text", required: true },
      { name: "question_key", label: "Câu", type: "text" },
      { name: "answer_text", label: "Đáp án", type: "textarea", required: true },
      { name: "elapsed_ms", label: "Mili giây", type: "number" },
      { name: "is_correct", label: "Đúng", type: "boolean" },
      { name: "awarded_points", label: "Điểm", type: "number" },
    ],
  },
  buzzers: {
    title: "Tín hiệu chuông",
    table: "buzzer_events",
    primaryKey: ["id"],
    orderBy: "id DESC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "room_id", label: "Phòng", type: "number", required: true },
      { name: "contestant_id", label: "Thí sinh", type: "number" },
      { name: "round_key", label: "Phần thi", type: "text", required: true },
      { name: "elapsed_ms", label: "Mili giây", type: "number" },
      { name: "status", label: "Trạng thái", type: "select", options: ["accepted", "locked", "foul"], required: true },
    ],
  },
  "speed-sequences": {
    title: "Chuỗi ảnh Tăng tốc",
    table: "speed_media_sequences",
    primaryKey: ["id"],
    orderBy: "question_set_id ASC, speed_stt ASC, sort_order ASC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "speed_stt", label: "Câu Tăng tốc", type: "number", required: true },
      { name: "media_url", label: "URL ảnh/video", type: "text", required: true },
      { name: "duration_seconds", label: "Số giây", type: "number", required: true },
      { name: "sort_order", label: "Thứ tự", type: "number" },
    ],
  },
  "tie-breaker": {
    title: "Câu hỏi phụ",
    table: "tie_breaker_questions",
    primaryKey: ["stt"],
    orderBy: "question_set_id ASC, stt ASC",
    columns: [
      { name: "stt", label: "STT", type: "number", generated: true },
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "question", label: "Câu hỏi", type: "textarea", required: true },
      { name: "answer", label: "Đáp án", type: "text", required: true },
      { name: "media_path", label: "Media", type: "text" },
    ],
  },
  jeopardy: {
    title: "MVT Jeopardy",
    table: "jeopardy_clues",
    primaryKey: ["id"],
    orderBy: "question_set_id ASC, category ASC, point_value ASC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "category", label: "Chủ đề", type: "text", required: true },
      { name: "point_value", label: "Điểm", type: "select", options: [5, 10, 15], required: true },
      { name: "clue_text", label: "Gợi ý", type: "textarea", required: true },
      { name: "answer", label: "Đáp án", type: "text", required: true },
      { name: "is_opened", label: "Đã mở", type: "boolean" },
    ],
  },
  "wall-sets": {
    title: "Only Connect - Tường liên kết",
    table: "connecting_wall_sets",
    primaryKey: ["id"],
    orderBy: "question_set_id ASC, id DESC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "question_set_id", label: "Bộ đề", type: "number", required: true },
      { name: "title", label: "Tên tường", type: "text", required: true },
      { name: "time_limit_seconds", label: "Thời gian", type: "number" },
    ],
  },
  "wall-cells": {
    title: "Only Connect - 16 ô",
    table: "connecting_wall_cells",
    primaryKey: ["id"],
    orderBy: "wall_id ASC, sort_order ASC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "wall_id", label: "Tường", type: "number", required: true },
      { name: "group_no", label: "Nhóm", type: "number", required: true },
      { name: "word_text", label: "Từ khóa", type: "text", required: true },
      { name: "group_answer", label: "Đáp án nhóm", type: "text", required: true },
      { name: "sort_order", label: "Thứ tự", type: "number" },
    ],
  },
  imports: {
    title: "Lịch sử nhập đề",
    table: "import_jobs",
    primaryKey: ["id"],
    orderBy: "id DESC",
    columns: [
      { name: "id", label: "ID", type: "number", generated: true },
      { name: "file_name", label: "Tệp", type: "text", required: true },
      { name: "format_key", label: "Định dạng", type: "select", options: ["q2t_standard", "lct3"], required: true },
      { name: "status", label: "Trạng thái", type: "select", options: ["uploaded", "imported", "failed"], required: true },
      { name: "message", label: "Thông báo", type: "textarea" },
    ],
  },
};

function getMeta(key) {
  return TABLES[key] || null;
}

function writableColumns(meta, mode) {
  return meta.columns.filter((col) => !(mode === "insert" && col.generated));
}

function quote(name) {
  return `\`${name}\``;
}

module.exports = { TABLES, getMeta, writableColumns, quote };
